site_name: greenmilkvvv
site_url: https://Greenmilkvvv.github.io

# 启用 Material 主题
theme:
  name: material

  palette:
    # 浅色模式配色
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink # 主色调：控制顶栏、链接等颜色
      accent: gray # 强调色：控制悬浮、按钮等交互元素颜色[citation:7]
    # 深色模式配色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange

  features:
    - navigation.tabs # 导航栏标签（如果已开启）
    - navigation.sections # 导航栏分区（如果已开启）
    # 以下是关键，添加切换器
    - navigation.top # 将切换按钮放在顶部导航栏
    - palette.toggle # 颜色调色板切换功能本身



  # 配置导航菜单
nav:
  - 首页: index.md
  # - 关于我: about.md
  # - 博客:
  #     - 第一篇博客: blog/post1.md
