site_name: 杉岛明菜
site_url: https://Greenmilkvvv.github.io


  # 配置导航菜单
nav:
  - 我: 
    - MyLife/index.md
    - 我的简述: MyLife/mylife.md
    - 你会记住我吗?: MyLife/name.md
  - 博客: 
    - Blogs/index.md
    - 数学: 
      - 广义感知器的收敛性: Blogs/Math_Stat_ML/广义感知器收敛性.md
      - 二次变分——背景, 定义和性质: Blogs\Math_Stat_ML\quadratic_variation.md
    - 冷战: 
      - 南越·中央情报办公室: Blogs/Cold_War/CIO_SouthVietnam.md
    - 书:
      - The Dogs of War: Blogs\Books\The Dogs of War (Foysyth).md
      - 球形の荒野: Blogs\Books\球形の荒野.md
      - Katanga 1960-63: Blogs\Books\Katanga 1960-63.md
      - Solo: Blogs\Books\Solo.md
    - 电影:
      - 无人知晓: Blogs\Films\无人知晓.md
    - MKdocs: 
      - KaTeX 跨行公式对齐问题: Blogs\MKDocs\formula_align.md
    - 车: 
      - 驾驶: 
        - Blogs\Cars\Skills\科目二 侧方停车.md
        - Blogs\Cars\Skills\科目二 直角转弯.md
        - Blogs\Cars\Skills\科目二 曲线行驶.md
        - Blogs\Cars\Skills\科目二 坡道定点停车 & 启动.md


  - 项目: 
    - Projects/index.md
    - CAPM模型在中国的有效性检验: Projects\CAPM_2025Aut\CAPM_test_A_share.md
  - 随笔: 
    - Essays/index.md
    - 日记: 
      - 2026.01.19: Essays/Diaries/26_01_19_night.md
      - 2026.01.20: Essays/Diaries/26_01_20.md
      - 2026.01.21: Essays/Diaries/26_01_21.md
      - 2026.01.22: Essays/Diaries/26_01_22.md
      - 2026.01.26: Essays/Diaries/26_01_26.md
      - 2026.01.28: Essays/Diaries/26_01_28.md
    - 吃: 
      - 小甜品: 
        - 草莓小蛋糕: Essays\Eating\小蛋糕_26_01_24.md
        - 焦糖海盐榛子千层: Essays\Eating\小蛋糕_26_01_26.md
      - 牛肉河粉 & 素春卷 (西贡妈妈): Essays\Eating\西贡妈妈_26_01_01.md
  - 转载: 
    - Reproduce/index.md
    - 歌词: 
      - Reproduce\Lyrics\Dear Heart.md
      - Reproduce\Lyrics\Eden (feat. 072).md
      - Reproduce\Lyrics\地球ぎ (地球仪).md
      - Reproduce\Lyrics\地球ぎ ポルトガル語ver.md
      - Reproduce\Lyrics\DOUBLE.md
      - Reproduce\Lyrics\不得.md
      - Reproduce\Lyrics\金魚花火 (金鱼花火).md
      - Reproduce\Lyrics\Autumn leaves don't fall.md
      - Reproduce\Lyrics\ROUND-MIRROR MOON.md
      - Reproduce\Lyrics\Don't Cry.md
      
  - 爱: 
    - Love/index.md
    - 忘记:
      - 2026.01.19: Love/Forget/20260119_1.md

# 启用 Material 主题
theme:
  name: material
  icon: 
    logo: material/heart-multiple
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: material/heart-multiple
  repo: fontawesome/brands/github

  palette:
    # 浅色模式：    
    - scheme: default
      primary: custom # blue grey
      accent: pink # blue grey
      toggle: # 这部分是给切换按钮定义图标和提示文字，可选
        icon: material/brightness-4
        name: Switch to dark mode
    # 深色模式：
    - scheme: slate
      primary: custom # blue grey
      accent: pink # blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit

  language: zh # 一些提示性的文字会变成中文


# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Greenmilkvvv/Greenmilkvvv.github.io
repo_name: Greenmilkvvv.github.io


extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | Greenmilkvvv
      icon: fontawesome/brands/github
      link: https://github.com/Greenmilkvvv
    - name: Kaggle | greenmilkvvv
      icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/greenmilkvvv
    - name: 小红书 | 桂花酒酿芝麻大元宵
      icon: simple/xiaohongshu
      link: https://www.xiaohongshu.com/user/profile/621b6d89000000001000cc67


markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes


extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css

  # 自定义颜色样式风格
  - stylesheets/extra.css




