site_name: greenmilkvvv
site_url: https://Greenmilkvvv.github.io



# 启用 Material 主题
theme:
  name: material
  palette:
    # 浅色模式：使用“默认”方案搭配粉色
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle: # 这部分是给切换按钮定义图标和提示文字，可选
        icon: material/brightness-4
        name: Switch to dark mode
    # 深色模式：使用“石板”方案搭配更深的粉色
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.top
    - palette.toggle



  # 配置导航菜单
nav:
  - 首页: index.md
  # - 关于我: about.md
  # - 博客:
  #     - 第一篇博客: blog/post1.md
